### ISSUE TITLE
Not clear which version of which components to deploy for a given release

### ISSUE THREAD

**Issue by dnmvisser** [OpenConext/OpenConext-deploy#172]
The [CHANGELOG](https://github.com/OpenConext/Stepup-Deploy/blob/master/CHANGELOG) lists the Release numbers, and which components to install. But it's not complete, for instance for release 15 it's not immediately clear which version of the `Stepup-tiqr` component to deploy.
Also, you'd have to manually browse each component's repository, check the released files, eyeball sort and pick the appropriate tarball.
Deployment could be eased by having a var that holds all components, their versions, and the actual URLs as well, for instance:

```
release_components:
  - 15:
    - Middleware:
      - version: 2.8.0
      - tarball_url: https://github.com/OpenConext/Stepup-Middleware/releases/download/2.8.0-20180419112655Z-aab35614eb074d5a1d775e1b1b35818c2e87011e/Stepup-Middleware-2.8.0-20180419112655Z-aab35614eb074d5a1d775e1b1b35818c2e87011e.tar.bz2
    - Gateway:
      - version: 2.9.0
      - tarball_url: https://github.com/OpenConext/Stepup-Gateway/releases/download/2.9.0-20180419111847Z-13486f5ae7c183200191ed0442a88642f09a3659/Stepup-Gateway-2.9.0-20180419111847Z-13486f5ae7c183200191ed0442a88642f09a3659.tar.bz2
    - SelfService:
      - version: 2.9.0
      - tarball_url: https://github.com/OpenConext/Stepup-SelfService/releases/download/2.9.0-20180419113528Z-48492cd60c412cbe0c7fdb6b262dfa80e44450da/Stepup-SelfService-2.9.0-20180419113528Z-48492cd60c412cbe0c7fdb6b262dfa80e44450da.tar.bz2
    - RA:
      - version: 2.9.0
      - tarball_url: https://github.com/OpenConext/Stepup-RA/releases/download/2.9.0-20180419113138Z-dc14e3b78b5aaf884db632e2f7d943a071e38a3f/Stepup-RA-2.9.0-20180419113138Z-dc14e3b78b5aaf884db632e2f7d943a071e38a3f.tar.bz2
    - tiqr:
      - version: 1.1.8
      - tarball_url: https://github.com/OpenConext/Stepup-tiqr/releases/download/1.1.8-20180306084707Z-acd4c5db5b22ff5fad48c032e0236fa27d1ae1ce/Stepup-tiqr-1.1.8-20180306084707Z-acd4c5db5b22ff5fad48c032e0236fa27d1ae1ce.tar.bz2
  - 14:
    - Middleware:
      - version: 2.7.1
      - tarball_url: https://github.com/OpenConext/Stepup-Middleware/releases/download/2.7.1-20180330083152Z-a3c457f93751ce97f6915326106515763b267594/Stepup-Middleware-2.7.1-20180330083152Z-a3c457f93751ce97f6915326106515763b267594.tar.bz2
    - Gateway:
      - version: 2.8.3
      - tarball_url: https://github.com/OpenConext/Stepup-Gateway/releases/download/2.8.3-20180404095536Z-c71690729b38ef4a570ea4c0a2cbd8e8b6fcbca5/Stepup-Gateway-2.8.3-20180404095536Z-c71690729b38ef4a570ea4c0a2cbd8e8b6fcbca5.tar.bz2
    - SelfService:
      - version: 2.8.0
      - tarball_url: https://github.com/OpenConext/Stepup-SelfService/releases/download/2.8.0-20180315090529Z-1ea292cf3ff8afc7e2edd1452c409b9d6de30ee8/Stepup-SelfService-2.8.0-20180315090529Z-1ea292cf3ff8afc7e2edd1452c409b9d6de30ee8.tar.bz2
    - RA:
      - version: 2.8.1
      - tarball_url: https://github.com/OpenConext/Stepup-RA/releases/download/2.8.1-20180323142543Z-92c7a9bb3cf74524398a7d5ae7b8d69eecae7406/Stepup-RA-2.8.1-20180323142543Z-92c7a9bb3cf74524398a7d5ae7b8d69eecae7406.tar.bz2
    - tiqr:
      - version: 1.1.8
      - tarball_url: https://github.com/OpenConext/Stepup-tiqr/releases/download/1.1.8-20180306084707Z-acd4c5db5b22ff5fad48c032e0236fa27d1ae1ce/Stepup-tiqr-1.1.8-20180306084707Z-acd4c5db5b22ff5fad48c032e0236fa27d1ae1ce.tar.bz2
  - 13.2:
    - etc
    etc
```
