### ISSUE TITLE
Undefined variables for Monitoring-Tests

### ISSUE THREAD

**Issue by precurse** [OpenConext/OpenConext-deploy#254]
Hello, we're in the midst of bringing up our Openconext-Deploy repo to the latest release. I've got most of the needed variables added to our deployment, but running into some errors for some that are undefined:

```
FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'metadata_sp_url'"}
```

The `monitoring-tests/templates/application.yml.j2` (https://github.com/OpenConext/OpenConext-deploy/blob/master/roles/monitoring-tests/templates/application.yml.j2#L15-L16) refers to these 2 variables:
```
  metadata_sp_url: {{ monitoring_tests.metadata_sp_url }}
  metadata_idp_url: {{ monitoring_tests.metadata_idp_url }}
```

But these don't exist anywhere in the `monitoring_tests` template:
https://github.com/OpenConext/OpenConext-deploy/blob/master/environments/template/group_vars/template.yml#L359-L364
```
monitoring_tests:
  mujina_idp_entity_id: http://mock-idp
  mujina_sp_base_url: https://mujina-sp.{{ base_domain }}
  person_id: "{{ monitoring_tests_person_id }}"
  user: monitor
  password: "{{ monitoring_tests_password }}"
```

Any idea what they should be set to? 

Thanks!
Andrew
