### ISSUE TITLE
database access for multiple-hosts setup

### ISSUE THREAD

**Issue by baszoetekouw** [OpenConext/OpenConext-deploy#93]
In the current templates, access to the databases is set up like this:

``` yml
- name: Create database user
  mysql_user: name={{ item[0].name }} host={{ item[1] }} password={{ item[0].password }} priv={{ item[0].db_name }}.*:ALL state=present
  with_nested:
    - "{{ databases.users }}"
    - "{{ database_clients }}"
```

where database_clients is defined as an array of ips in the appropriate secrets file. 

However, this grant a little bit too much access (i.e., access to databases for java apps is also allowed from php hosts).  It would be nicer (I guess) to tie the apprioriate hosts closed to the user by specifying them in the database.users variable.  I don't know ansible well enough though how to write the loop in case there are multiple hosts, for example when database.user si defined like this:

``` yml
databases:
  names:
    - teams
  users:
    - { name: teamsrw, db_name: teams, hosts: [{{dbhost1}},{{dbhost2}}], password: "{{ mysql_passwords.teams }}" }
```

(and btw, `databases.names` seems superfluous, as the same information is contained in `databases.users`)
